# Generated by Django 5.0.6 on 2026-06-04 10:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('short_description', models.TextField(max_length=500)),
                ('long_description', models.TextField()),
                ('location', models.CharField(help_text='e.g., Pokhara, Annapurna Region, Himalayas', max_length=255)),
                ('start_point', models.CharField(default='Pokhara', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('easy_moderate', 'Easy to Moderate'), ('moderate', 'Moderate'), ('moderate_challenging', 'Moderate to Challenging'), ('challenging', 'Challenging'), ('very_challenging', 'Very Challenging')], max_length=30)),
                ('max_altitude', models.PositiveIntegerField(help_text='In meters')),
                ('max_altitude_feet', models.PositiveIntegerField(help_text='In feet')),
                ('best_season', models.CharField(choices=[('all_year', 'All Year Round'), ('spring_autumn', 'Spring & Autumn (Best)'), ('march_may', 'March-May'), ('september_november', 'September-November'), ('march_november', 'March-November')], max_length=50)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='trek_images/hero/')),
                ('image_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for images')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.TextField(blank=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-is_popular', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='treks_trek_slug_b9739d_idx'), models.Index(fields=['difficulty'], name='treks_trek_difficu_9ca504_idx'), models.Index(fields=['price_usd'], name='treks_trek_price_u_89366b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MapCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_coordinates', to='treks.trek')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='treks.trek')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExcludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_items', to='treks.trek')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrekImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trek_images/gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='treks.trek')),
            ],
            options={
                'ordering': ['trek', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('altitude', models.CharField(blank=True, max_length=100)),
                ('trekking_hours', models.CharField(blank=True, max_length=50)),
                ('accommodation', models.CharField(blank=True, max_length=100)),
                ('meals_included', models.CharField(default='Breakfast, Lunch, Dinner', max_length=100)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='treks.trek')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('trek', 'day_number')},
            },
        ),
    ]
