# Generated by Django 5.0.6 on 2026-06-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=50)),
                ('page_identifier', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField(max_length=500)),
                ('meta_keywords', models.TextField()),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True, max_length=500)),
                ('og_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('page_type', 'page_identifier')},
            },
        ),
    ]
